name: reproduce figures

on:
  push:
  schedule:
    - cron: '0 0 2 * *'  # run once per month
  workflow_dispatch:

jobs:
  in-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Initialisation
      uses: actions/checkout@v3

    - name: Build and test inside container
      run: docker build -t testimage docker
